name: Deploy Apps
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy_fe:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    env:
      VITE_API_URL: https://naijastars-api.classroomio.com/api

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: 'deno install'

      - name: Build step
        run: 'deno task fe:build'

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'naijastars'
          entrypoint: 'vite_server.ts'
          root: 'dist'

  deploy_api:
    name: Deploy API
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GITHUB_TOKEN: ${{ secrets.API_GITHUB_TOKEN }}

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install step
        run: 'deno install'

      - name: Build step
        run: 'deno task fe:build'

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: 'naijastars-api'
          entrypoint: 'main.ts'
          root: '.'
